import React, { useState } from 'react';
import Navbar from '../components/Navbar';
import ImageUploader from '../components/ImageUploader';
import ResultCard from '../components/ResultCard';
import TreatmentCard from '../components/TreatmentCard';
import LoadingSpinner from '../components/LoadingSpinner';
import { diseaseService } from '../services/services';
import { ImageIcon, AlertCircle } from 'lucide-react';

// Disease remedies - Now using backend API for comprehensive, up-to-date recommendations
// (Previously stored locally, now generated by remedy_generation_service.py)
// The backend provides detailed, farmer-friendly information from disease_information_db.py

const LeafDisease = () => {
  const [selectedImage, setSelectedImage] = useState(null);
  const [result, setResult] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  const handleImageSelect = (file) => {
    setSelectedImage(file);
    setResult(null);
    setError('');
  };

  const handleSubmit = async (e) => {
    e.preventDefault();

    if (!selectedImage) {
      setError('Please upload an image');
      return;
    }

    setLoading(true);
    setError('');
    setResult(null);

    try {
      const formData = new FormData();
      formData.append('file', selectedImage);

      // Step 1: Detect disease
      const data = await diseaseService.detectLeafDisease(formData);
      
      const predictedCrop = data.crop || 'Unknown';
      const predictedDisease = data.disease || 'Unknown';
      const confidence = data.confidence || 0;
      const isHealthy = predictedDisease.toLowerCase() === 'healthy';

      // Create friendly disease display name
      const getFriendlyDiseaseName = (disease) => {
        if (disease.toLowerCase() === 'healthy') {
          return 'Healthy (No Disease Detected)';
        }
        return disease;
      };

      // Set loading state with initial result
      setResult({
        crop: predictedCrop,
        disease: predictedDisease,
        diseaseName: getFriendlyDiseaseName(predictedDisease),
        isHealthy: isHealthy,
        confidence: `${(confidence * 100).toFixed(1)}%`,
        confidenceValue: confidence,
        remedy: isHealthy ? 'Plant is Healthy' : 'Generating detailed recommendations...',
        pesticide: '...',
        prevention: '...',
        action: '...',
        severity: data.severity || 'Unknown',
        isLoading: true,
        source: 'loading'
      });

      // Step 2: Generate detailed remedies
      try {
        const remedyResponse = await diseaseService.generateRemedy({
          crop: predictedCrop,
          disease: predictedDisease,
          isHealthy: isHealthy
        });

        // Update result with detailed remedies
        setResult(prevResult => ({
          ...prevResult,
          remedy: remedyResponse.remedy || prevResult.remedy,
          pesticide: remedyResponse.pesticide || prevResult.pesticide,
          prevention: remedyResponse.prevention || prevResult.prevention,
          action: remedyResponse.action || prevResult.action,
          severity: data.severity || 'Unknown',
          isLoading: false,
          source: remedyResponse.source || 'database'
        }));
      } catch (remedyError) {
        console.warn('Could not generate detailed remedies:', remedyError);
        
        // Provide fallback recommendations
        const fallbackInfo = {
          remedy: 'Detailed recommendation information is currently unavailable.',
          pesticide: 'Please consult with local agricultural extension office.',
          prevention: 'Maintain proper field sanitation and crop rotation practices.',
          action: 'Contact agricultural officer for accurate diagnosis and treatment.',
          source: 'fallback'
        };

        setResult(prevResult => ({
          ...prevResult,
          remedy: fallbackInfo.remedy,
          pesticide: fallbackInfo.pesticide,
          prevention: fallbackInfo.prevention,
          action: fallbackInfo.action,
          isLoading: false,
          source: fallbackInfo.source
        }));
      }
    } catch (err) {
      console.error('Error detecting disease:', err);
      setError(
        err.response?.data?.detail || 
        err.message || 
        'Failed to analyze image. Please ensure the backend server is running.'
      );
    }
    setLoading(false);
  };

  const handleReset = () => {
    setSelectedImage(null);
    setResult(null);
    setError('');
  };

  return (
    <div className="page-container">
      <Navbar />
      
      <div className="page-content">
        <div className="max-w-4xl mx-auto">
          <div className="mb-8">
            <h1 className="text-3xl font-bold text-gray-800 mb-2 flex items-center">
              <ImageIcon className="w-8 h-8 mr-3 text-primary-600" />
              Plant Leaf Disease Detection
            </h1>
            <p className="text-gray-600">Upload leaf images to identify diseases</p>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
            <div className="lg:col-span-2">
              <div className="card">
                <form onSubmit={handleSubmit}>
                  <ImageUploader
                    onImageSelect={handleImageSelect}
                    label="Upload Plant Leaf Image"
                    accept="image/png, image/jpeg, image/jpg"
                  />

                  {error && (
                    <div className="mt-4 p-3 bg-red-50 border border-red-200 rounded-lg flex items-start">
                      <AlertCircle className="w-5 h-5 text-red-600 mr-2 flex-shrink-0 mt-0.5" />
                      <p className="text-sm text-red-600">{error}</p>
                    </div>
                  )}

                  <div className="flex space-x-3 mt-6">
                    <button 
                      type="submit" 
                      disabled={loading || !selectedImage} 
                      className="btn-primary flex-1"
                    >
                      {loading ? 'Classifying..' : 'Classify Disease'}
                    </button>
                    <button 
                      type="button" 
                      onClick={handleReset} 
                      className="btn-secondary"
                    >
                      Reset
                    </button>
                  </div>
                </form>
              </div>

              <div className="card mt-6 bg-green-50 border border-green-200">
                <h3 className="text-lg font-semibold text-green-800 mb-3">Supported Crops</h3>
                <div className="grid grid-cols-2 gap-2 text-sm text-gray-700">
                  <div>• Apple</div>
                  <div>• Blueberry</div>
                  <div>• Cherry</div>
                  <div>• Corn</div>
                  <div>• Grape</div>
                  <div>• Orange</div>
                  <div>• Peach</div>
                  <div>• Pepper</div>
                  <div>• Potato</div>
                  <div>• Raspberry</div>
                  <div>• Soybean</div>
                  <div>• Squash</div>
                  <div>• Strawberry</div>
                  <div>• Tomato</div>
                </div>
              </div>

              <div className="card mt-6 bg-blue-50 border border-blue-200">
                <h3 className="text-lg font-semibold text-blue-800 mb-3">Tips for Best Results</h3>
                <ul className="space-y-2 text-sm text-gray-700">
                  <li>• Capture leaf against plain background</li>
                  <li>• Ensure good lighting (natural light preferred)</li>
                  <li>• Include the entire leaf or affected area</li>
                  <li>• Avoid shadows and reflections</li>
                  <li>• Image should be in focus</li>
                </ul>
              </div>
            </div>

            <div className="lg:col-span-1">
              <div className="lg:sticky lg:top-24 self-start">
                {loading ? (
                  <div className="card">
                    <LoadingSpinner text="Analyzing leaf..." />
                  </div>
                ) : result ? (
                  <>
                    {/* Result Summary Card */}
                    <div className={`card ${result.isHealthy ? 'bg-green-50 border border-green-200' : 'bg-orange-50 border border-orange-200'}`}>
                          <div className="flex items-start justify-between mb-4">
                            <div>
                              <h3 className={`text-sm font-semibold ${result.isHealthy ? 'text-green-800' : 'text-orange-800'}`}>
                                {result.isHealthy ? '✓ Healthy' : '⚠ Disease Detected'}
                              </h3>
                            </div>
                          </div>
                          
                          <div className="space-y-3">
                            {/* Crop Name (Auto-Detected) */}
                            <div className="flex justify-between items-center">
                              <span className="text-sm text-gray-600">Crop:</span>
                              <span className="text-sm font-semibold text-gray-900">{result.crop}</span>
                            </div>
                            
                            {/* Disease Name */}
                            <div className="flex justify-between items-center">
                              <span className="text-sm text-gray-600">Status:</span>
                              <span className={`text-sm font-semibold ${result.isHealthy ? 'text-green-700' : 'text-orange-700'}`}>
                                {result.diseaseName}
                              </span>
                            </div>
                            
                            {/* Confidence Score */}
                            <div className="flex justify-between items-center pt-2 border-t">
                              <span className="text-sm text-gray-600">Confidence:</span>
                              <div className="flex items-center space-x-2">
                                <span className="text-sm font-semibold text-gray-900">{result.confidence}</span>
                                <div className="w-16 bg-gray-200 rounded-full h-2">
                                  <div
                                    className={`h-2 rounded-full transition-all ${
                                      result.confidenceValue >= 0.8 
                                        ? 'bg-green-500' 
                                        : result.confidenceValue >= 0.6 
                                        ? 'bg-yellow-500' 
                                        : 'bg-orange-500'
                                    }`}
                                    style={{ width: `${result.confidenceValue * 100}%` }}
                                  />
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>

                        {/* Remedy Card */}
                        {result.remedy && result.pesticide && result.action && (
                          <TreatmentCard
                            disease={result.disease}
                            crop={result.crop}
                            remedy={result.remedy}
                            pesticide={result.pesticide}
                            prevention={result.prevention || result.action}
                            action={result.action}
                            confidence={result.confidenceValue}
                            isHealthy={result.isHealthy}
                            source={result.source}
                          />
                        )}
                  </>
                ) : (
                  <div className="card bg-gray-50">
                    <p className="text-gray-500 text-center text-sm">
                      Upload a leaf image to detect diseases
                    </p>
                  </div>
                )}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default LeafDisease;
